# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abds6FvZW_AUHXZGksY7Fn-tuuZXMDNx
"""

!unzip "/content/Hotel Reservations (1).csv.zip" -d "/content/"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Hotel Reservations (1).csv")



df.info()

df.head()



df["total_nights"] = (
    df["no_of_weekend_nights"] +
    df["no_of_week_nights"]
)

df.drop(columns=["no_of_weekend_nights","no_of_week_nights"], inplace=True)

df["no_of_special_requests"].value_counts()

df.groupby("booking_status")["lead_time"].describe()

df_corr = df.copy()

df_corr["booking_status"] = df_corr["booking_status"].map({
    "Not_Canceled": 0,
    "Canceled": 1
})

corr_matrix = df_corr.corr(numeric_only=True)

corr_matrix["booking_status"].sort_values(ascending=False)

df.groupby("booking_status")["no_of_special_requests"].mean()

df["no_of_adults"].value_counts()

df[df["no_of_adults"] == 0]

df[df["no_of_adults"] == 0][
    ["no_of_adults",
     "no_of_children",
     "booking_status"]
].head(20)

df[df["no_of_adults"] == 0]["booking_status"].value_counts(normalize=True)

df[df["no_of_adults"] > 0]["booking_status"].value_counts(normalize=True)

df_corr = df.copy()

df_corr['booking_status']=df_corr["booking_status"].map({"Not_Canceled": 0, "Canceled": 1})
corr_matrix=df_corr.corr(numeric_only=True)
corr_matrix

df.hist(bins=50, figsize=(20,15))
plt.show()

def split_train_test(data, test_ratio):
  shuffeledindices=np.random.permutation(len(data))
  test_set_size=int(len(data)*test_ratio)
  train_set=shuffeledindices[:test_set_size]
  test_set=shuffeledindices[test_set_size:]
  return   data.iloc[test_set] , data.iloc[train_set]

train_set, test_set=split_train_test(df, 0.2)

train_set.value_counts()

df["total_previous_bookings"] = (
    df["no_of_previous_cancellations"] +
    df["no_of_previous_bookings_not_canceled"]
)

df["family"] = (
    df["no_of_adults"] +
    df["no_of_children"]
)
df["cancellation_ratio"] = (
    df["no_of_previous_cancellations"] /
    (df["total_previous_bookings"] + 1)

  )
df["price_per_guest"] = (
    df["avg_price_per_room"] /
    (df["family"] + 1)
)
df["booking_urgency"] = (
    df["lead_time"] /
    (df["total_nights"] + 1)
)

pd.crosstab(
    df["room_type_reserved"],
    df["booking_status"],
    normalize="index"
)

train_set.groupby("booking_status")["repeated_guest"].mean()

pd.crosstab(
    df["market_segment_type"],
    df["booking_status"],
    normalize="index"
)

df["market_segment_type"].value_counts()

df["booking_status"].value_counts()

from sklearn.model_selection import train_test_split

df

for col in [
    "total_nights",
    "family",
    "price_per_guest",
    "booking_urgency",
    "cancellation_ratio",
    "total_previous_bookings"
]:
    print("\n", col)
    print(df.groupby("booking_status")[col].mean())

y=df['booking_status']
X=df[[
    "no_of_adults",
    "no_of_children",

    "type_of_meal_plan",
    "required_car_parking_space",
    "room_type_reserved",

    "lead_time",

    "arrival_month",
    "arrival_date",

    "market_segment_type",

    "repeated_guest",
    "no_of_previous_cancellations",
    "no_of_previous_bookings_not_canceled",

    "avg_price_per_room",
    "no_of_special_requests",

    "total_nights",
    "family",
    "total_previous_bookings",
    "price_per_guest",
    "booking_urgency"
]]

df

cat_features = [
    "type_of_meal_plan",
    "room_type_reserved",
    "market_segment_type"

]
num_features = [
    "no_of_adults",
    "no_of_children",
    "required_car_parking_space",
    "lead_time",
    "arrival_month",
    "arrival_date",
    "repeated_guest",
    "no_of_previous_cancellations",
    "no_of_previous_bookings_not_canceled",
    "avg_price_per_room",
    "no_of_special_requests",
    "total_nights",
    "family",
    "total_previous_bookings",
    "price_per_guest",
    "booking_urgency"
]

X = df
y=y

X

y

test_set

df

from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(X, y):
    strat_train_set = X.loc[train_index]
    strat_test_set = X.loc[test_index]

strat_train_set

strat_test_set

strat_train_set = strat_train_set.drop("Booking_ID", axis=1)
strat_test_set = strat_test_set.drop("Booking_ID", axis=1)

hotel = strat_train_set.copy()

hotel

hotel_X = hotel

hotel_y =y

hotel_X

hotel_y

hotel_X = strat_train_set.copy()
hotel_y = y.iloc[train_index].copy()

strat_test_set

hotel_y

train_index

len(train_index)

len(train_index)
import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(data=pd.DataFrame({"booking_status": hotel_y}),
              x="booking_status")
plt.show()

sns.boxplot(
    x=hotel_y,
    y=hotel_X["lead_time"]
)
plt.show()

sns.boxplot(
    x=hotel_y,
    y=hotel_X["no_of_special_requests"]
)
plt.show()

pd.crosstab(
    df["market_segment_type"],
    df["booking_status"],
    normalize="index"
).plot(kind="bar", stacked=True)
plt.show()

plt.figure(figsize=(12,8))

sns.heatmap(
    hotel_X.select_dtypes(include="number").corr(),
    cmap="coolwarm",
    annot=False
)

plt.show()

from pandas.plotting import scatter_matrix

attributes = [
    "lead_time",
    "avg_price_per_room",
    "no_of_special_requests",
    "total_nights",
    "price_per_guest"
]

scatter_matrix(
    hotel_X[attributes],
    figsize=(10,8)
)

plt.show()

df.plot(kind="scatter",x="lead_time",y="no_of_special_requests", alpha=0.1)

plt.scatter(x=df["lead_time"],y=df["booking_status"], alpha=1.0,s=df['market_segment_type'])

import seaborn as sns

sns.scatterplot(
    data=df,
    x="lead_time",
    y="avg_price_per_room",
    hue="market_segment_type",
    style="booking_status",
    alpha=0.7
)

sns.boxplot(
    x="booking_status",
    y="lead_time",
    data=df
)

sns.boxplot(
    x="booking_status",
    y="no_of_special_requests",
    data=df
)

pd.crosstab(
    df["market_segment_type"],
    df["booking_status"],
    normalize="index"
).plot(kind="bar", stacked=True)

corr_matrix=df.corr(numeric_only=True)
corr_matrix[].sort_values(ascending=False)

df["type_of_meal_plan"] = df["type_of_meal_plan"].map({
"Meal Plan 1" :1,
"Not Selected":0,
"Meal Plan 2"	:2,
"Meal Plan 3":3

})

df

DF

cor_matrix=df.corr(numeric_only=True)
cor_matrix["booking_status"].sort_values(ascending=False)

hotel = strat_train_set.copy()

hotel_labels = y.iloc[train_index].copy()

hotel

hotel_labels

num_cols = [
    'no_of_adults',
    'no_of_children',
    'required_car_parking_space',
    'lead_time',
    'arrival_month',
    'arrival_date',
    'repeated_guest',
    'no_of_previous_cancellations',
    'no_of_previous_bookings_not_canceled',
    'avg_price_per_room',
    'no_of_special_requests',
    'total_nights',
    'family',
    'total_previous_bookings',
    'price_per_guest',
    'booking_urgency'
]
cat_cols = [
    'type_of_meal_plan',
    'room_type_reserved',
    'market_segment_type'
]

X

y

hotel_y=hotel_y.map({
    "Not_Canceled": 0,
    "Canceled": 1
})

hotel_y

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
    ("scaler", StandardScaler())
])
from sklearn.preprocessing import OneHotEncoder

cat_pipeline = Pipeline([
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

hotel_y.value_counts()

hotel_prepared = preprocessor.fit_transform(hotel)
hotel_prepared

hotel_prepared.shape

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(hotel_prepared, hotel_y)

model.score(hotel_prepared, hotel_y)

predictions = model.predict(hotel_prepared)

some_data=hotel.iloc[:5]
some_labels=hotel_y.iloc[:5]
some_data_prepared=preprocessor.transform(some_data)
prediction=model.predict(some_data_prepared)

from sklearn.metrics import accuracy_score

accuracy_score(hotel_y, predictions)

from sklearn.metrics import classification_report

print(classification_report(
    hotel_y,
    predictions
))

from sklearn.metrics import confusion_matrix

confusion_matrix(
    hotel_y,
    predictions
)

hotel_labels

from sklearn.metrics import accuracy_score

accuracy_score(hotel_y, predictions)

from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model,
    hotel_prepared,
    hotel_y,
    cv=5,
    scoring="accuracy"
)

print(scores)
print(scores.mean())
print(scores.std())

hotel_prepared

from sklearn.metrics import precision_score , recall_score ,f1_score ,roc_curve ,roc_auc_score

precision_score(
    hotel_y,
    predictions
)

recall_score(
    hotel_y,
    predictions
)

f1_score(
    hotel_y,
    predictions
)

fpr , tpr , thresholds = roc_curve(
    hotel_y,
    predictions
)

def plot_roc_curve(fpr, tpr,lable=None):
    plt.plot(fpr, tpr, color="orange", label="ROC")
    plt.plot([0, 1], [0, 1], color="darkblue", linestyle="--")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC Curve")
    plt.legend()
    plt.show()

plot_roc_curve(fpr, tpr)

from sklearn.metrics import RocCurveDisplay

y_scores = model.predict_proba(hotel_prepared)[:,1]

RocCurveDisplay.from_predictions(
    hotel_y,
    y_scores
)

