# -*- coding: utf-8 -*-
"""Function_tranformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArskWPUdHHgm14CeDIBxP91RxpUdF2Ve
"""

import pandas as pd
ds = pd.read_csv("hf://datasets/phihung/titanic/train.csv")

df

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

df.head()

df.drop(columns=['Embarked'],inplace=True)

X=df.drop(columns=['Survived'])
Y=df['Survived']
X_train, X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)



X_train

X_test

Y_train

Y_test

df.isnull().sum()

imputer = SimpleImputer(strategy='mean')
imputer.fit(X_train[['Age']])
X_train_age = imputer.transform(X_train[['Age']])
X_test_age = imputer.transform(X_test[['Age']])

X_train_age_1=np.array(X_train_age).reshape(1,-1)
X_test_age_1=np.array(X_test_age).reshape(1,-1)

X_train_age_1





X_train_rem=X_train.drop(columns=['Age'])
X_test_rem=X_test.drop(columns=['Age'])

X_train_transformed=np.concatenate((X_train_rem,X_train_age),axis=1)

X_train_transformed

import seaborn as sns
import scipy.stats as stats

X_train_transformed[:, 0]

plt.figure(figsize=(14,10))
plt.subplot(121)
sns.distplot(X_train_transformed[:, 1])
plt.title('Age')
plt.subplot(122)
stats.probplot(X_train_transformed[:, 1],dist='norm',plot=plt)
plt.title('AgeQQ')
plt.show()

plt.figure(figsize=(14,10))
plt.subplot(121)
sns.distplot(X_train_transformed[:, 0])
plt.title('Fare')
plt.subplot(122)
stats.probplot(X_train_transformed[:, 1],dist='norm',plot=plt)
plt.title('Fare')
plt.show()



from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

import pandas as pd
df = pd.read_csv("hf://datasets/phihung/titanic/train.csv")

df.drop(columns=['PassengerId','Ticket','Cabin','Name'],inplace=True)
X_train, X_test,Y_train,Y_test=train_test_split(df.drop(columns=["Survived"]),df["Survived"],test_size=0.2,random_state=42)

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
X_train

numerical_features = ['Age', 'Fare', 'SibSp', 'Parch', 'Pclass']
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', MinMaxScaler())
])

categorical_features = ['Sex', 'Embarked']
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='passthrough' # 'passthrough' will keep any columns not specified above
)

classifier = DecisionTreeClassifier()

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', classifier)
])

pipeline.fit(X_train,Y_train)

from sklearn import set_config
set_config(display='diagram')

set_config(display='text')

from sklearn.model_selection import cross_val_score,GridSearchCV,RandomizedSearchCV

cross_val_score(pipeline,X_train,Y_train,cv=5,scoring='accuracy')

cross_val_score(pipeline,X_train,Y_train,cv=5,scoring='accuracy').mean()

random_search = RandomizedSearchCV(pipeline, param_distributions, scoring='accuracy', n_iter=10, random_state=42)

random_search

ds

from sklearn.preprocessing import FunctionTransformer
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score



def make_model(function,dataset):
  function=function
  dataset=dataset.copy()
  dataset.drop(columns=['Embarked','PassengerId','Pclass','Name','Sex','SibSp','Parch','Ticket','Cabin',],inplace=True)
  X=dataset.drop(columns=['Survived'])
  Y=dataset['Survived']
  X_train, X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
  imputer = SimpleImputer(strategy='mean')
  imputer.fit(X_train[['Age']])
  X_train_age = imputer.transform(X_train[['Age']])
  X_test_age = imputer.transform(X_test[['Age']])
  X_train_rem=X_train.drop(columns=['Age'])
  X_test_rem=X_test.drop(columns=['Age'])
  X_train_transformed=np.concatenate((X_train_rem,X_train_age),axis=1)
  X_test_transformed=np.concatenate((X_test_rem,X_test_age),axis=1)

  trf=FunctionTransformer(function)
  trf.fit(X_train_transformed)
  X_train_transformed_1=trf.transform(X_train_transformed)
  X_test_transformed_1=trf.transform(X_test_transformed)

  clf1=DecisionTreeClassifier()
  clf2=RandomForestClassifier()
  clf3=GradientBoostingClassifier()


  clf1.fit(X_train_transformed_1,Y_train)
  clf2.fit(X_train_transformed_1,Y_train)
  clf3.fit(X_train_transformed_1,Y_train)

  y_pred1=clf1.predict(X_test_transformed_1)
  y_pred2=clf2.predict(X_test_transformed_1)
  y_pred3=clf3.predict(X_test_transformed_1)
  clf1.fit(X_train_transformed_1,Y_train)

  print('Accuracy_score',accuracy_score(Y_test,y_pred1))
  print('Accuracy_score',accuracy_score(Y_test,y_pred2))
  print('Accuracy_score',accuracy_score(Y_test,y_pred3))


  plt.figure(figsize=(20,14))
  plt.subplot(221)
  # 'Age' is at index 0 in X DataFrame
  stats.probplot(X.iloc[:, 0],dist='norm',plot=plt)
  plt.title('Before actual transformation : Age')
  plt.subplot(222)
  # 'Age' is at index 1 in X_train_transformed_1 NumPy array
  stats.probplot(X_train_transformed_1[:, 1],dist='norm',plot=plt)
  plt.title('AgeQQ , After Transformation')


  plt.subplot(223)
  # 'Fare' is at index 1 in X DataFrame
  stats.probplot(X.iloc[:, 1],dist='norm',plot=plt)

  plt.title('Fare')
  plt.subplot(224)
  # 'Fare' is at index 0 in X_train_transformed_1 NumPy array
  stats.probplot(X_train_transformed_1[:, 0],dist='norm',plot=plt)
  plt.title('Fare')
  plt.show()

make_model(np.log1p,ds)

