# -*- coding: utf-8 -*-
"""poly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kcFMINWc9pV2T_E5rhBYQ_PbMUYLoz-p
"""

import numpy as np
import matplotlib.pyplot as plt

m=100
X=6*np.random.rand(m,1)-3
y=0.5*X**2+X+2+np.random.randn(m,1)

from sklearn.preprocessing import PolynomialFeatures
poly_features=PolynomialFeatures(degree=2,include_bias=False)
X_poly=poly_features.fit_transform(X)

X[0]

X_poly[0]

from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(X_poly,y)

lin_reg.intercept_, lin_reg.coef_

from sklearn.preprocessing import PolynomialFeatures
poly_features1=PolynomialFeatures(degree=1,include_bias=False)
X_poly1=poly_features1.fit_transform(X)
from sklearn.linear_model import LinearRegression
lin_reg1=LinearRegression()
lin_reg1.fit(X_poly1,y)

lin_reg1.intercept_, lin_reg1.coef_

from sklearn.preprocessing import PolynomialFeatures
poly_features1=PolynomialFeatures(degree=10,include_bias=False)
X_poly10=poly_features1.fit_transform(X)
from sklearn.linear_model import LinearRegression
lin_reg10=LinearRegression()
lin_reg10.fit(X_poly10,y)
lin_reg10.intercept_, lin_reg10.coef_

plt.plot(X,y,"b.")
plt.plot(X,lin_reg.predict(X_poly),"r-")
plt.plot(X,lin_reg1.predict(X_poly1),"g-")
plt.plot(X,lin_reg10.predict(X_poly10),"y-")
plt.legend(["original","degree 2","degree 1","degree10"])
plt.show()

from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split


def plot_learning_curves(model,X,y):
  X_train , X_val,y_train,y_val=train_test_split(X,y,test_size=0.2)
  train_errors,val_errors=[],[]
  for m in range(1,len(X_train)):
    model.fit(X_train[:m],y_train[:m])
    y_train_predict=model.predict(X_train[:m])
    y_val_predict=model.predict(X_val)
    train_errors.append(mean_squared_error(y_train[:m],y_train_predict))
    val_errors.append(mean_squared_error(y_val,y_val_predict))
  plt.plot(np.sqrt(train_errors),"r-+",linewidth=2,label="train")
  plt.plot(np.sqrt(val_errors),"b-",linewidth=3,label="val")
  plt.legend()
  plt.xlabel("Training set size")
  plt.ylabel("RMSE")
  plt.show()

lin_reg=LinearRegression()
plot_learning_curves(lin_reg,X,y)



from sklearn.pipeline import Pipeline
polynomial_regression=Pipeline([
    ("poly_features",PolynomialFeatures(degree=5,include_bias=False)),
    ("lin_reg",LinearRegression()),
])
plot_learning_curves(polynomial_regression,X,y)
#

"""RIDGE , LASSO , ELASTIC NET ARE THE LOGISTIC (CLASSIFICATION) REGULARIZATION TECHNIQUES"""

from sklearn.preprocessing import StandardScaler
std_slr=StandardScaler()
std_slr.fit(X)
X_std=std_slr.transform(X)
y_std=std_slr.fit_transform(y)

print(type(X))
print(X.shape)
print(X.dtype)

X_std[0]

from sklearn.linear_model import Ridge
ridge_reg=Ridge(alpha=1,solver="cholesky")
ridge_reg.fit(X_std,y_std)
ridge_reg.predict([[1.5]])

from sklearn.linear_model import SGDRegressor
sgd_reg=SGDRegressor()
sgd_reg.fit(X_std,y_std)

from sklearn.linear_model import SGDRegressor
sgd_regl2=SGDRegressor(penalty="l2")
sgd_regl2.fit(X_std,y_std)

from sklearn.linear_model import SGDRegressor
sgd_regl1=SGDRegressor(penalty="l1")
sgd_regl1.fit(X_std,y_std)

import numpy as np
import matplotlib.pyplot as plt
plt.plot(X,y,"b.")
plt.plot(X,sgd_reg.predict(X),"r-+")
plt.plot(X,sgd_regl2.predict(X),"r-")
plt.plot(X,sgd_regl1.predict(X),"g-")
plt.legend(["original","l2","l1"])
plt.show()

sgd_reg.predict([[1.5]])

from sklearn.linear_model import Lasso
lasso_reg=Lasso(alpha=0.1)
lasso_reg.fit(X,y)

print(X_std.mean())
print(X_std.std())

import numpy as np
from sklearn.base import clone
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import SGDRegressor
import copy
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

# Split data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Create Polynomial + Scaling Pipeline
poly_scaler = Pipeline([
    ("poly_features", PolynomialFeatures(degree=90, include_bias=False)),
    ("std_scaler", StandardScaler()),
])

# Transform the data
X_train_poly_scaled = poly_scaler.fit_transform(X_train)
X_val_poly_scaled = poly_scaler.transform(X_val)

# SGD Regressor
sgd_reg = SGDRegressor(
    max_iter=1,
    tol=None,
    penalty=None,
    eta0=0.0005,
    learning_rate="constant",
    random_state=42,
    warm_start=True
)

y_train = y_train.ravel()
y_val = y_val.ravel()

# Variables to store the best model
minimum_val_error = float("inf")
best_epoch = None
best_model = None

# Training Loop
for epoch in range(1000):

    # Train for one epoch
    sgd_reg.fit(X_train_poly_scaled, y_train.ravel())

    # Predict on validation set
    y_val_predict = sgd_reg.predict(X_val_poly_scaled)

    # Calculate validation error
    val_error = mean_squared_error(y_val, y_val_predict)

    # Save the best model
    if val_error < minimum_val_error:
        minimum_val_error = val_error
        best_epoch = epoch
        best_model = copy.deepcopy(sgd_reg)
# Results

print(f"Best Epoch            : {best_epoch}")
print(f"Minimum Validation MSE: {minimum_val_error:.6f}")

from sklearn import datasets
iris=datasets.load_iris()
list(iris.keys())

X=iris["data"][:,3:]
y=(iris["target"]==2).astype(int)

from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X,y)

X_new = np.linspace(0,3,1000).reshape(-1,1)
y_proba=log_reg.predict_proba(X_new)

# plt.plot(X_new,y_proba,"b-")
plt.plot(X_new,y_proba[:,1],"g-",label="Iris Virginica")
plt.plot(X_new,y_proba[:,0],"b--",label="Not Iris Virginica")
plt.grid("minor")
plt.legend()
plt.show()

log_reg.score(X,y)

log_reg.coef_

X_new

log_reg.predict([[1.6],[1.9]])

X

plt.plot(iris[""])