# -*- coding: utf-8 -*-
"""Random_for.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkCNIC_sv0AlhENaVQ3x8eNx58FzIz4R
"""

from sklearn.datasets import make_moons,load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,VotingClassifier,BaggingClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import numpy as np

make_moon=make_moons(n_samples=10000,noise=0.4,random_state=42)

X_train,X_test,y_train,y_test=train_test_split(make_moon[0],make_moon[1],test_size=0.2,random_state=42)

y_train

rf=RandomForestClassifier(n_estimators=100,random_state=42)
dt=DecisionTreeClassifier(random_state=42)
sgd=SGDClassifier(random_state=42)

vo_clr=VotingClassifier(
    estimators=[
        ('rf',rf),
        ('dt',dt),
        ('sgd',sgd)
    ],
    n_jobs=-1,
    voting='hard',

)

vo_clr.fit(X_train,y_train)

for clf in (rf,dt,sgd,vo_clr):
    clf.fit(X_train,y_train)
    y_pred=clf.predict(X_test)
    print(clf.__class__.__name__,accuracy_score(y_test,y_pred))

bag_clr=BaggingClassifier(
    DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=100,
    bootstrap=True,
    n_jobs=-1,
    oob_score=True
)

bag_clr.fit(X_train,y_train)

from sklearn.metrics import accuracy_score
y_pred=bag_clr.predict(X_test)
accuracy_score(y_test,y_pred)

bag_clr.oob_decision_function_

ran_for_clr=RandomForestClassifier(n_estimators=500,max_leaf_nodes=16,n_jobs=-1,bootstrap=True,max_samples=110,oob_score=True,random_state=42)
# ran_for_clr.fit(X_train,y_tra

from sklearn.model_selection import cross_val_predict
ran_for_clr.fit(X_train,y_train)

y_pred_rf=ran_for_clr.predict(X_test)
accuracy_score(y_test,y_pred_rf)

ran_for_clr.oob_score_

ran_for_clr.feature_importances_

ran_for_clr.estimator_params

from sklearn.tree import ExtraTreeClassifier

ExtraTreeClassifier()

Extra_reg=ExtraTreeClassifier(
    max_leaf_nodes=16,
    random_state=42,
    criterion='entropy',
    splitter='random',
    max_depth=None,
    min_samples_split=3,
    min_samples_leaf=5,
    # min_weight_fraction_leaf=0.0,
    max_features=4    # min_impurity_decrease=0.0


)

Extra_reg.fit(X_train,y_train)

ypred_extra=Extra_reg.predict(X_test)

accuracy_score(ypred_extra,y_test)

iris=load_iris()

ran_forest_for_iris=RandomForestClassifier(n_estimators=500,n_jobs=-1,random_state=42,bootstrap=True,max_samples=100,oob_score=True)

ran_forest_for_iris.fit(iris['data'],iris['target'])

for name, score in zip(iris['feature_names'], ran_forest_for_iris.feature_importances_):
  print(name, score)



X = iris["data"][:, 3:]   # Petal width
y = (iris["target"] == 2).astype(int)   # Iris-Virginica or not

from sklearn.datasets import fetch_openml
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt


# Plot feature importances

# Load MNIST
mnist = fetch_openml("mnist_784", as_frame=False)

X = mnist.data
y = mnist.target

# Train Random Forest
rnd_clf = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

rnd_clf.fit(X, y)

plt.imshow(
    rnd_clf.feature_importances_.reshape(28, 28),
    cmap="hot",
    interpolation="nearest"
)
plt.colorbar()
plt.axis("off")

plt.savefig("iris.png", dpi=300, bbox_inches="tight")

plt.show()

import joblib
joblib.dump(rnd_clf, "rnd_clf.pkl")

X

make_moon=make_moons(n_samples=10000,noise=0.4,random_state=42)

X_train,X_test,y_train,y_test=train_test_split(make_moon[0],make_moon[1],test_size=0.2,random_state=42)

y_train

from sklearn.ensemble import AdaBoostClassifier

ada_clr=AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=1),
    n_estimators=20,
    # algorithm=,
    learning_rate=0.5,
)

ada_clr.fit(X_train,y_train)

from sklearn.metrics import accuracy_score
y_pred=ada_clr.predict(X_test)
accuracy_score(y_test,y_pred)

np.random.seed(42)

X = np.linspace(-0.0111, 3.6, 500).reshape(-1, 1)
y = X[:, 0]**3 + np.random.randn(500) * 10

plt.scatter(X, y)
plt.show()

from sklearn.ensemble import GradientBoostingRegressor

gradient_reg=GradientBoostingRegressor(max_depth=2,n_estimators=100,learning_rate=0.3,random_state=42)

gradient_reg.fit(X,y)

from sklearn.model_selection import cross_val_score

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_train.shape

cross_val_score(gradient_reg,X_train,y_train,scoring='neg_mean_squared_error',cv=5)

from sklearn.metrics import mean_squared_error
y_pred=gradient_reg.predict(X_test)
mean_squared_error(y_test,y_pred)

from sklearn.metrics import mean_absolute_error
# mean_absolute_error(y_test,y_pred)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

gbrt=GradientBoostingRegressor(max_depth=2,n_estimators=120)

gbrt.fit(X_train,y_train)

errors=[mean_squared_error(y_test,y_pred) for y_pred in gbrt.staged_predict(X_test)]



best_n_estimator=np.argmin(errors)

best_n_estimator

grbt_best=GradientBoostingRegressor(max_depth=2,n_estimators=best_n_estimator)

grbt_best.fit(X_train,y_train)

original_mean=mean_squared_error(y_test,gbrt.predict(X_test))
actual_after_best=mean_squared_error(y_test,grbt_best.predict(X_test))

original_mean

actual_after_best

improvement = original_mean - actual_after_best
print(improvement)

improvement_percent = (
    (original_mean - actual_after_best) / original_mean
) * 100

print(improvement_percent)

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

gbrt_sq=GradientBoostingRegressor(max_depth=2,warm_start=True)

min_val=float('inf')
error_going_up=0
for n_estimator in range(1,300):
    gbrt_sq.n_estimators=n_estimator
    gbrt_sq.fit(X_train,y_train)
    y_pred=gbrt_sq.predict(X_test)
    val_error=mean_squared_error(y_test,y_pred)
    if val_error<min_val:
      min_val=val_error
      error_going_up=0
    else:
      error_going_up+=1
      if error_going_up==5:
        break

gbrt_sq.n_estimators_

np.random.seed(42)

X = np.linspace(-0.11, 3, 500).reshape(-1, 1)
y = X[:, 0]**3 + np.random.randn(500) * 10

plt.scatter(X, y)
plt.show()

import xgboost

xg_boost=xgboost.XGBRegressor()
xg_boost.fit(X_train,y_train)

y_pred_xg=xg_boost.predict(X_test)

xg_boost_as=xgboost.XGBRegressor()

from xgboost import XGBRegressor

xg_boost_as = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    early_stopping_rounds=2,
    random_state=42
)

xg_boost_as.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=True
)

