# -*- coding: utf-8 -*-
"""Decision_tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOxGpof2iiaQar0TjGKEqxaapS6_WtYT
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

from sklearn.tree import DecisionTreeClassifier

iris=load_iris()
X=iris.data[:,2:]
y=iris.target

dec_tree_clrf=DecisionTreeClassifier(max_depth=2,min_samples_split=10,max_leaf_nodes=10)
dec_tree_clrf.fit(X,y)

from sklearn.tree import export_graphviz
export_graphviz(
    dec_tree_clrf,
    out_file="iris_tree.dot",
    feature_names=iris.feature_names[2:],
    class_names=iris.target_names,
    rounded=True,
    filled=True
)

!dot -Tpng iris_tree.dot -o iris_tree.png

import matplotlib.pyplot as plt

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8))

plot_tree(
    dec_tree_clrf,
    feature_names=iris.feature_names[2:],
    class_names=iris.target_names,
    filled=True,
    rounded=True,
    fontsize=11
)

plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Create a mesh grid
x0 = np.linspace(X[:,0].min()-1, X[:,0].max()+1, 500)
x1 = np.linspace(X[:,1].min()-1, X[:,1].max()+1, 500)

xx, yy = np.meshgrid(x0, x1)

X_new = np.c_[xx.ravel(), yy.ravel()]
y_pred = dec_tree_clrf.predict(X_new)
y_pred = y_pred.reshape(xx.shape)

# Plot decision regions
plt.figure(figsize=(8,6))
plt.contourf(xx, yy, y_pred, alpha=0.3, cmap=plt.cm.Pastel2)
plt.contour(xx, yy, y_pred, colors="k", linewidths=1)

# Plot training samples
plt.scatter(X[:,0], X[:,1], c=y, cmap=plt.cm.Set1, edgecolor="black", s=60)

plt.xlabel("Petal length (cm)")
plt.ylabel("Petal width (cm)")
plt.title("Decision Tree Decision Boundaries")

plt.show()

dec_tree_clrf.predict_proba([[5,1.5]])

dec_tree_clrf.predict([[1,0]])

X=3+2*np.random.rand(100,1)
y=1+2*X+np.random.rand(100,1)

from sklearn.tree import DecisionTreeRegressor
tree_reg=DecisionTreeRegressor(max_depth=2)
tree_reg.fit(X,y)

export_graphviz(
    tree_reg,
    out_file="iris_tree_reg.dot",
    feature_names=['Feature 0'],
    rounded=True,
    filled=True
)

!dot -Tpng iris_tree_reg.dot -o iris_tree_reg.png

from sklearn.tree import DecisionTreeRegressor
tree_reg1=DecisionTreeRegressor(max_depth=3,)
tree_reg1.fit(X,y)

tree_reg4=DecisionTreeRegressor(max_depth=5,)
tree_reg4.fit(X,y)

import numpy as np
import matplotlib.pyplot as plt
# Generate smooth x values
X_new = np.linspace(X.min(), X.max(), 500).reshape(-1, 1)

# Predict
y_pred = tree_reg.predict(X_new)

# Plot
plt.figure(figsize=(8,5))

plt.scatter(X, y, color="blue", s=20, label="Training Data")
plt.plot(X_new, y_pred, color="red", linewidth=2, label="Decision Tree Prediction")

plt.xlabel("X")
plt.ylabel("y")
plt.title("Decision Tree Regression (max_depth=2)")
plt.legend()


# Generate smooth x values
X_new = np.linspace(X.min(), X.max(), 500).reshape(-1, 1)

# Predict
y_pred = tree_reg1.predict(X_new)

# Plot
plt.figure(figsize=(8,6))

plt.scatter(X, y, color="blue", s=20, label="Training Data")
plt.plot(X_new, y_pred, color="red", linewidth=2, label="Decision Tree Prediction")

plt.xlabel("X")
plt.ylabel("y")
plt.title("Decision Tree Regression (max_depth=3)")
plt.legend()

# Generate smooth x values
X_new = np.linspace(X.min(), X.max(), 500).reshape(-1, 1)

# Predict
y_pred = tree_reg4.predict(X_new)

# Plot
plt.figure(figsize=(8,5))

plt.scatter(X, y, color="blue", s=20, label="Training Data")
plt.plot(X_new, y_pred, color="red", linewidth=2, label="Decision Tree Prediction")

plt.xlabel("X")
plt.ylabel("y")
plt.title("Decision Tree Regression (max_depth=4)")
plt.legend()

plt.show()



