# -*- coding: utf-8 -*-
"""PIPELINE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArskWPUdHHgm14CeDIBxP91RxpUdF2Ve
"""

import pandas as pd
df = pd.read_csv("hf://datasets/phihung/titanic/train.csv")

df

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

df.head()

df.drop(columns=['PassengerId','Ticket','Cabin','Name'],inplace=True)

df.drop(columns=['PassengerId','Ticket','Cabin','Name'],inplace=True)
X_train, X_test,Y_train,Y_test=train_test_split(df.drop(columns=["Survived"]),df["Survived"],test_size=0.2,random_state=42)

X_train

X_test

Y_train

Y_test

df.isnull().sum()

imputer = SimpleImputer(strategy='mean')
imputer.fit(X_train[['Age']])
X_train_age = imputer.transform(X_train[['Age']])
X_test_age = imputer.transform(X_test[['Age']])



impute = SimpleImputer(strategy='most_frequent')
impute.fit(X_train[['Embarked']])
X_train_embarked = impute.transform(X_train[['Embarked']])
X_test_embarked = impute.transform(X_test[['Embarked']])

one_hot_embarked=OneHotEncoder(handle_unknown='ignore')
one_hot_sex=OneHotEncoder(handle_unknown='ignore')
X_train_embarked = one_hot_embarked.fit_transform(X_train_embarked).toarray()
X_train_sex=one_hot_sex.fit_transform(X_train[['Sex']]).toarray()
X_test_sex=one_hot_sex.transform(X_test[['Sex']]).toarray()
X_test_embarked=one_hot_embarked.transform(X_test_embarked).toarray()

X_train_embarked

X_train_rem=X_train.drop(columns=['Sex','Embarked','Age'])
X_test_rem=X_test.drop(columns=['Sex','Embarked','Age'])

X_train_transformed=np.concatenate((X_train_rem,X_train_embarked,X_train_sex,X_train_age),axis=1)

X_test_transformed=np.concatenate((X_test_rem,X_test_embarked,X_test_sex,X_test_age),axis=1)

clf=DecisionTreeClassifier()
clf.fit(X_train_transformed,Y_train)

y_pred=clf.predict(X_test_transformed)

plt.plot(Y_test)

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

import pandas as pd
df = pd.read_csv("hf://datasets/phihung/titanic/train.csv")

df.drop(columns=['PassengerId','Ticket','Cabin','Name'],inplace=True)
X_train, X_test,Y_train,Y_test=train_test_split(df.drop(columns=["Survived"]),df["Survived"],test_size=0.2,random_state=42)

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
X_train

numerical_features = ['Age', 'Fare', 'SibSp', 'Parch', 'Pclass']
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', MinMaxScaler())
])

categorical_features = ['Sex', 'Embarked']
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='passthrough' # 'passthrough' will keep any columns not specified above
)

classifier = DecisionTreeClassifier()

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', classifier)
])

pipeline.fit(X_train,Y_train)

from sklearn import set_config
set_config(display='diagram')

set_config(display='text')

