# -*- coding: utf-8 -*-
"""svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGL76_oUYDXjhYwkWkOYrQIGWAYCnPx8
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons,load_iris
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

from sklearn.svm import SVC,LinearSVC
from sklearn.preprocessing import StandardScaler

svc_clf=Pipeline([
    ("poly_fear",PolynomialFeatures(degree=3)),
    ("scaler",StandardScaler()),
    ("svm_clf",SVC(kernel="linear",degree=3,coef0=1,C=5))
])

iris= load_iris()
X=iris["data"][:,(2,3)]
y=(iris["target"]==2).astype(np.float64)

plt.plot(X[y==0,0],X[y==0,1],"bs")
plt.plot(X[y==1,0],X[y==1,1],"g^")
plt.show()

svc_clf.fit(X,y)

svc_clf.predict([[5.5,1.7]])

import joblib
joblib.dump(svc_clf,"iris_svc.pkl")

linear_svc_clf=Pipeline([
    ("poly_fear",PolynomialFeatures(degree=3)),
    ("scaler",StandardScaler()),
    ("svm_clf",LinearSVC(C=1,loss="hinge"))
])

linear_svc_clf.fit(X,y)

linear_svc_clf.predict([[5.5,1.7]])

from sklearn.linear_model import SGDClassifier

non_linear_svc_clr=Pipeline([
    ("poly_fear",PolynomialFeatures(degree=3)),
    ("scaler",StandardScaler()),
    ("svm_clf",LinearSVC(C=10,loss="hinge"))
])

X,y=make_moons(n_samples=100,noise=0.15)

non_linear_svc_clr.fit(X,y)

non_linear_svc_clr.predict([[0.5,0.5]])

plt.plot(X[y==0,0],X[y==0,1],"bs")
plt.plot(X[y==1,0],X[y==1,1],"g^")
plt.plot(non_linear_svc_clr.predict([[0.5,0.5]]),"y*")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Plot training data
plt.plot(X[y==0,0], X[y==0,1], "bs")
plt.plot(X[y==1,0], X[y==1,1], "g^")

# Create a grid
x0 = np.linspace(X[:,0].min()-0.2, X[:,0].max()+0.2, 500)
x1 = np.linspace(X[:,1].min()-0.2, X[:,1].max()+0.2, 500)
xx, yy = np.meshgrid(x0, x1)

# Predict every point on the grid
X_new = np.c_[xx.ravel(), yy.ravel()]
y_pred = non_linear_svc_clr.predict(X_new)
y_pred = y_pred.reshape(xx.shape)

# Draw decision boundary
plt.contour(xx, yy, y_pred, levels=[0.5], colors='red', linewidths=2)
plt.contourf(xx, yy, y_pred, alpha=0.2, cmap=plt.cm.Paired)
plt.contour(xx, yy, y_pred, levels=[0.5], colors="red", linewidths=2)
plt.show()

