# -*- coding: utf-8 -*-
"""tm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwALqCOhuF07j7tmRj7J_ueqNOOJN2F5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

X=2*np.random.rand(100,1)
y=4+3*X+np.random.rand(100,1)



X_b=np.c_[np.ones((100,1)),X]



theta_top=np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

theta_top

X_new=np.array([[0],[2]])
X_new

X_new_n=np.c_[np.ones((2,1)),X_new]
X_new_n

y_predict=X_new_n.dot(theta_top)
y_predict

plt.plot(X_new_n,y_predict,"r-",label="Predictions")
plt.plot(X,y,".",label="Training Data")
plt.axis([0,2.2,0,12])
plt.legend()
plt.show()





plt.plot(X,".")

from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(X,y)

import joblib
joblib.dump(lin_reg,"lin_reg.pkl")

lin_reg.intercept_,lin_reg.coef_

lin_reg.predict(X_new)

from scipy.linalg import lstsq

Q_best_svd,residuals,rank,s=lstsq(X_b,y
                                  )

Q_best_svd,residuals,rank,s

residuals

psedo_inverse=np.linalg.pinv(X_b).dot(y)
psedo_inverse

eta=
n_itr=1000
m=100

theta=np.random.randn(2,1)
theta

import numpy as np
import matplotlib.pyplot as plt

theta_path = []

def plot_gradient_descent(theta, eta):
    m = len(X_b)

    plt.scatter(X, y, s=10)

    for iteration in range(4975):

        if iteration < 10:
            y_predict = X_new_n.dot(theta)
            plt.plot(X_new, y_predict, "b-")

        gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
        theta = theta - eta * gradients

    plt.xlabel("x")
    plt.axis([0, 2, 0, 15])
    plt.title(f"$\\eta$ = {eta}")


np.random.seed(42)
theta = np.random.randn(2,1)

plt.figure(figsize=(12,4))

plt.subplot(131)
plot_gradient_descent(theta.copy(), eta=0.25127790999487254)

plt.subplot(132)
plot_gradient_descent(theta.copy(), eta=0.1)

plt.subplot(133)
plot_gradient_descent(theta.copy(), eta=0.5)

plt.show()



theta0_hist = []
theta1_hist = []

for itr in range(n_itr):
    grad = 2/m * X_b.T.dot(X_b.dot(theta) - y)
    theta = theta - eta * grad

    theta0_hist.append(theta[0,0])
    theta1_hist.append(theta[1,0])

plt.plot(theta0_hist, label="theta0")
plt.plot(theta1_hist, label="theta1")
plt.legend()
plt.show()

from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import GridSearchCV

param_grid = {
    "eta0": [0.001, 0.01, 0.1],
    "max_iter": [1000, 5000, 10000]
}

model = SGDRegressor(
    learning_rate="constant",
    random_state=42
)

grid = GridSearchCV(
    model,
    param_grid,
    cv=5,
    scoring="neg_mean_squared_error"
)

grid.fit(X, y.ravel())

print(grid.best_params_)
print(grid.best_score_)

etas = [0.001, 0.01, 0.1, 0.5]
iterations = [100, 500, 1000]

best_cost = float("inf")
best_params = None

for eta in etas:
    for n_iter in iterations:

        theta = np.random.randn(2,1)

        for _ in range(n_iter):
            gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
            theta = theta - eta * gradients

        cost = np.mean((X_b.dot(theta)-y)**2)

        if cost < best_cost:
            best_cost = cost
            best_params = (eta, n_iter)

print(best_params)
print(best_cost)

import numpy as np

best_cost = float("inf")
best_params = None

n_trials = 50

for _ in range(n_trials):

    # Random hyperparameters
    eta = 10 ** np.random.uniform(-4, 0)   # 0.0001 to 1
    n_iter = np.random.randint(100, 5000)

    theta = np.random.randn(2,1)

    for _ in range(n_iter):
        gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
        theta = theta - eta * gradients

    cost = np.mean((X_b.dot(theta) - y)**2)

    if cost < best_cost:
        best_cost = cost
        best_params = {
            "eta": eta,
            "n_iter": n_iter
        }

print("Best Params:", best_params)
print("Best Cost:", best_cost)

